# Generated by Django 4.2 on 2024-10-19 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rule"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="rule",
            table="rule",
        ),
    ]
