# Generated by Django 4.2 on 2024-10-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_rule_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                (
                    "department",
                    models.IntegerField(
                        choices=[
                            (1, "Sales"),
                            (2, "Marketing"),
                            (3, "Human Resources"),
                            (4, "Information Technology"),
                            (5, "Finance"),
                        ],
                        null=True,
                    ),
                ),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("experience", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="rule",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="rule",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rule",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="rule",
            name="ast",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rule",
            name="rule_string",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name="rule",
            table=None,
        ),
    ]
