# Generated by Django 4.2 on 2024-10-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_employee_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(default="default", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rule",
            name="name",
            field=models.CharField(default="rule-default", max_length=255),
            preserve_default=False,
        ),
    ]
